### ISSUE TITLE
no moudule named pythia.utils.phoc.cphoc

### ISSUE THREAD

**Issue by w867066886** [HAWLYQ/Qc-TextCap#1]
请问这个错误是为什么，我按您给的链接安装后运行报这个错

**Comment by w867066886** [comment]
另外可以給一個完整的安装教程吗，因为好像装不上去

**Comment by HAWLYQ** [comment]
感谢您的建议，我们会尽快整理出完整的安装教程。

**Comment by HAWLYQ** [comment]
我们已经更新了完整的安装教程，并且在ubuntu 16.04.5, cuda 10.0.130上进行了测试。
