### ISSUE TITLE
请问bua_feats/obj/536e0b7ee067169c.npy  和bua_feats/ocr下面的npy是什么文件呀

### ISSUE THREAD

**Issue by w867066886** [HAWLYQ/Qc-TextCap#2]
如题

**Comment by w867066886** [comment]
提示我缺少这两个文件

**Comment by HAWLYQ** [comment]
您好，这两个文件夹下存放的都是bua抽取的region-level features，obj下是根据object bbox抽取来的，ocr下是根据ocr bbox抽取来的。这些特征需要自行抽取，我们在Dataset introduction部分有提到。

**Comment by w867066886** [comment]
谢谢您的回答，另外，在bottom-up-attention模型中提取的是obj特征，ocr特征是用的微软的接口提取的吗，这两部分是不参与训练的是吗

**Comment by HAWLYQ** [comment]
ocr的bbox是微软的接口提供的，特征也是用bua根据ocr的bbox抽取的，特征提取部分不参与训练。
