### ISSUE TITLE
提取scene text region features时，Azure OCR API获取的bbox的坐标值带有角度，应该如何处理？

### ISSUE THREAD

**Issue by iimmortall** [HAWLYQ/Qc-TextCap#4]
您好，我在按照论文里的方法使用Azure OCR API提取bboxes的时候，发现API返回的boundingBox为4个点的坐标（左上角开始，顺时针）， bottom-up-attention提取的bbox只有2个点的坐标，这里需要特殊处理吗？另外能够提供已经提取的object region features和scene text region features？

**Comment by HAWLYQ** [comment]
您好，我们在azure返回的结果上进行过一次后处理，使得bbox符合bua的输入形式，我们已经将处理过的bbox的信息保存在了数据文件中，不需要您重新处理；我们的特征文件有几十个G，目前还没有找到合适的方式分享这些文件，我们会继续想办法将其公开的。

**Comment by iimmortall** [comment]
请问bbox的信息保存在云盘imdb路径下的npy文件里的ocr_normalized_boxes字段里吗？我直接使用bottom-up-attention依据该字段的bbox信息提取特征就能得到scene text region features特征吗？

**Comment by HAWLYQ** [comment]
您需要乘以图像的height和width（我们也存在了数据文件里）得到原始bbox的坐标，然后作为bua的输入。

**Comment by HAWLYQ** [comment]
您需要乘以图像的height和width（我们也存在了数据文件里）得到原始bbox的坐标，然后作为bua的输入。

**Comment by HAWLYQ** [comment]
即[x_min, y_min,x_max, y_max] * [width,height,width, height]

**Comment by iimmortall** [comment]
我发现bottom-up-attention提取的obj的bbox数据和您提供的imdb路径下的npy文件里的obj_normalized_boxes字段数据(已经分别乘以图像的height和width)不一致，请问这里可以直接使用bottom-up-attention提取的obj特征吗？还是需要使用您提供的obj_normalized_boxes数据去提取obj特征？

**Comment by HAWLYQ** [comment]
需要用我们提供的bbox

**Comment by iimmortall** [comment]
好的，您们提供的bbox的坐标(float)乘以图像的height和width之后，需要转换成int吗?

**Comment by HAWLYQ** [comment]
不用的
