### ISSUE TITLE
CIDEr测试结果的和论文里不一致

### ISSUE THREAD

**Issue by iimmortall** [HAWLYQ/Qc-TextCap#5]
您好，我使用run_test_controltextcaps.sh和eval_QcTextCap.sh推理您提供的模型(rand模式训练)，在TextCaps test数据集上得到的CIDEr为349.3，这与您论文里的238.20(Table 3)或381.11(Table 1)不匹配，我哪里操作有问题吗？

**Comment by HAWLYQ** [comment]
您好，可以提供一个obj或者ocr的特征文件吗？我对比一下，看看是不是特征的问题。

**Comment by iimmortall** [comment]
[百度云盘地址](https://pan.baidu.com/s/1Nf7p2T0zWIZX4TNXbm9U0g)  密码: cvj1

**Comment by HAWLYQ** [comment]
您好，我比较了一下，特征是一样的。我重新跑了一下，可以复现论文的结果，我把GQAM_rand_controltextcaps最新的测试log文件和在测试集上的预测文件上传到了百度云盘目录中 (https://pan.baidu.com/s/1g8GzWAu0gVRlxGiphgDmsg, pwd:w4a6，分别存在该模型目录的reports文件夹和logs文件夹下），希望对您有帮助。

**Comment by iimmortall** [comment]
您好，使用您提供的reports进行评估可以得到和论文一致的结果(CIDEr 238.2)，应该是在inference阶段有问题，猜测可能是inference阶段引入了GT信息。我使用的脚本、代码、模型都是按照ReadMe说明文件进行设置的，我检查过我的代码，未没有异常改动，暂时未定位到问题。

**Comment by HAWLYQ** [comment]
您可以试试其他模型或者另外一个数据集，看看能不能复现论文的结果。

**Comment by iimmortall** [comment]
您好，我已经找到问题了，在inference阶段，应该修改GQAM_rand.yml配置文件中的use_model_and_auto_simpel_cap和use_model_simple_cap参数为`"use_model_and_auto_simpel_cap": false, "use_model_simple_cap": true`。您可以在ReadMe中添加该条说明，感谢您的解答。

**Comment by HAWLYQ** [comment]
好的，这是我的疏忽，非常感谢您的提醒！
